export const UPDATE_VALUE = 'UPDATE VALUE';

export const UPDATE_RACE = 'UPDATE RACE';

export const UPDATE_CLASS = 'UPDATE CLASS';

export const UPDATE_SKILL = 'UPDATE SKILL';

export const UPDATE_ABILITY = 'UPDATE ABILITY';

export const UPDATE_ALL_ABILITIES = 'UPDATE ALL ABILITIES';

export const FETCH_DATA = "FETCH DATA";
