export const UPDATE_VALUE = 'UPDATE VALUE';

export const UPDATE_RACE = 'UPDATE RACE';

export const UPDATE_CLASS = 'UPDATE CLASS';

export const UPDATE_SKILL = 'UPDATE SKILL';

export const UPDATE_ABILITY = 'UPDATE ABILITY';

export const UPDATE_ALL_ABILITIES = 'UPDATE ALL ABILITIES';

export const REQUEST_DATA = 'REQUEST DATA';

export const RECEIVE_DATA = 'RECEIVE DATA';

export const REQUEST_CHAR_DATA = 'REQUEST CHAR DATA';

export const RECEIVE_CHAR_DATA = 'RECEIVE CHAR DATA';
